# Generated by Django 5.1.3 on 2024-12-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_appointment_crop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crop',
            new_name='Appointment',
        ),
    ]
