# Generated by Django 5.1.3 on 2024-12-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_appointment_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='Crop',
        ),
    ]
